---

- name: NGINX | Installing NGINX
  sudo: yes
  apt:
    name: nginx
    state: latest
    update_cache: yes
 
- name: NGINX | Starting NGINX
  sudo: yes
  service:
    name: nginx
    state: started

# - name: Copy nginx configuration 
#   template: src=default.conf dest=/etc/nginx/conf.d/default.conf
#   notify: restart nginx

- name: Copy nginx configuration 
  sudo: yes
  copy: 
    src : templates/default.conf
    dest: /etc/nginx/conf.d/default.conf
  notify: restart nginx